services:
  db:
    build: .
    container_name: postgres18-task
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ../practice_data:/var/lib/postgresql

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru-RU"

  adminer:
    image: adminer
    container_name: adminer-task
    restart: always
    ports:
      - "8080:8080"

    depends_on:
      - db